if vim.g.neovide then
    vim.g.neovide_padding_top = 10
    vim.g.neovide_padding_bottom = 0
    vim.g.neovide_padding_left = 0
    vim.g.neovide_padding_right = 0
    vim.g.neovide_hide_mouse_when_typing = true
    vim.g.neovide_refresh_rate_idle = 10
    vim.g.neovide_refresh_rate = 100
    vim.g.neovide_no_idle = true
    vim.g.neovide_cursor_animation_length = 0.045
    vim.g.neovide_cursor_antialiasing = true
    vim.g.neovide_cursor_smooth_blink = true
    vim.g.neovide_cursor_vfx_mode = "torpedo"
    vim.g.neovide_cursor_vfx_particle_speed = 88.2
    vim.g.neovide_underline_stroke_scale = 1.4
    -- vim.g.neovide_cursor_vfx_particle_phase = 9400.5
    vim.g.neovide_cursor_vfx_particle_curl = 2.05
    vim.g.neovide_cursor_vfx_particle_phase = 120
    vim.g.neovide_cursor_vfx_opacity = 180.0
    vim.g.neovide_cursor_vfx_particle_density = 842.0
    vim.g.neovide_cursor_vfx_particle_lifetime = 2.0
    -- vim.g.neovide_cursor_vfx_particle_density = 400
    -- vim.g.neovide_cursor_vfx_particle_lifetime = 3.4
    vim.opt.linespace = 0
    vim.cmd "set guicursor=a:block"
    -- vim.o.guifont = "Input Mono Condensed GO:h19:#e-subpixelantialias:#h-none"
    -- vim.o.guifont = "RecMonoL880X Nerd Font:h18.5:#e-subpixelantialias:#h-none"
    vim.o.guifont = "TheFutureMono Nerd Font:h17:b:#e-subpixelantialias:#h-none"
    -- vim.o.guifont = "Maple Mono NF:h16.0:b:#e-subpixelantialias:#h-full"
    -- vim.o.guifont = "Recursive Mono Linear Static EB:b:h18:#e-subpixelantialias:#h-none"
    -- vim.g.neovide_transparency = 0.68
    vim.g.neovide_text_gamma = 1.8
    vim.g.neovide_text_contrast = 0.4
    vim.g.neovide_floating_shadow = true
    vim.g.neovide_window_blurred = true
    vim.g.neovide_floating_blur_amount_x = 50.0
    vim.g.neovide_floating_blur_amount_y = 40.0
    vim.g.neovide_floating_blur_amount_x = 32
    vim.g.neovide_floating_blur_amount_y = 32
    vim.g.neovide_floating_z_height = 10
    vim.g.neovide_light_angle_degrees = 45
    vim.g.neovide_light_radius = 5
    vim.g.neovide_show_border = true
    vim.g.neovide_scroll_animation_length = 0.288
    vim.g.neovide_cursor_trail_size = 0.882
    vim.cmd "set termguicolors"
    vim.g.neovide_cursor_animate_in_insert_mode = true
    vim.g.neovide_remember_window_size = true
    vim.g.neovide_cursor_animate_command_line = true
    vim.g.neovide_scale_factor = 1.0
end
