[colors.bright]
black = "#7081d0"
# blue = "#a48cf2"
blue = "#3359cc"
cyan = "#66e4fd"
green = "#A4FF90"
# magenta = "#FD92CE"
magenta = "#9071f4"
red = "#f16c75"
white = "#ebfafa"
yellow = "#F3D246"

[colors.cursor]
cursor = "#37f499"
text = "#f8f8f2"

# [colors.dim]
# black = "#42474B"
# blue = "#158393"
# cyan = "#0E9783"
# green = "#5F9E71"
# magenta = "#875B92"
# red = "#C6476C"
# white = "#BFC0C2"
# yellow = "#CD7F31"

[colors.normal]
black = "#21222c"
# blue = "#9071f4"
blue = "#4A9DF8"
cyan = "#04d1f9"
green = "#37f499"
# magenta = "#f265b5"
magenta = "#a48cf2"
red = "#f9515d"
white = "#fffff0"
yellow = "#F1A239"

[colors.primary]
background = "#212337"
foreground = "#ebfafa"

[colors.selection]
background = "#bf4f8e"
text = "#ebfafa"
