[colors.primary]
background = "#1b1d1e"
foreground = "#f8f8f2"

[colors.normal]
black = "#464741"
red = "#ff4a44"
yellow = "#e6db74"
blue = "#819aff"
green = "#a6e22e"
cyan = "#66d9ef"
white = "#f8f8f2"
magenta = "#f92672"

[colors.bright]
black = "#7e8e91"
red = "#ff4a44"
yellow = "#fd971f"
blue = "#ae81ff"
green = "#00ff87"
cyan = "#66d9ef"
white = "#f8f8f2"
magenta = "#f92672"
