# Colors (Solarized Osaka)
# HSL convert HEX using https://colordesigner.io/

# Default colors
[colors.primary]
background =  '#002B36'
foreground = '#b1c1e1'

# Normal colors
[colors.normal]
black   = '#1C1B19' #color.base04
red     = '#dc322f' #color.red
green   = '#859900' #color.green
yellow  = '#b58900' #color.yellow
blue    = '#268bd2' #color.blue
magenta = '#6c71c4' #color.magenta
cyan    = '#2aa198' #color.cyan
white   = '#b1c1e1' #color.base2

# Bright colors
[colors.bright]
black   = '#475B62'
red     = '#dc322f' #color.red300
green   = '#859900' #color.green300
yellow  = '#b58900' #color.yellow300
blue    = '#268bd2' #color.blue300
magenta = '#6c71c4' #color.magenta300
cyan    = '#2aa198' #color.cyan300
white   = '#b1c1e1' #color.base3
