# Default colors
[colors.primary]
background = '#3E3838'
foreground = '#FBF2F3'

# Normal colors
[colors.normal]
black = '#3E3838'
red = '#DF7484'
green = '#BBD87E'
yellow = '#EDCE73'
blue = '#DC9373'
magenta = '#A9AAE9'
cyan = '#A4D7CC'
white = '#FBF2F3'

# Bright colors
[colors.bright]
black = '#70696A'
red = '#DF7484'
green = '#BBD87E'
yellow = '#EDCE73'
blue = '#DC9373'
magenta = '#A9AAE9'
cyan = '#A4D7CC'
white = '#FBF2F3'

[colors.cursor]
cursor = '#FBF2F3'
text = '#3E3838'
